import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from './(components)/navbar'
import { ColorPicker } from './(components)/color'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'David Samson',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen">
          <Navbar />
          <div style={{height:'calc(100vh - var(--navbar-height))'}}>
            {children}
          </div>
          <ColorPicker />
        </div>
      </body>
    </html>
  )
}