import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './(components)/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'David Samson',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex flex-col">
          <Navbar />
          <div className="flex-grow">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}


// // make a navbar component
// const Navbar = () => {
//     return (
//         <div>
//             <h1>My Navbar</h1>
//         </div>
//     )
// }